export const colors = {
  black: '#00321F',
  lightestGray: '#F7F7F7',
  darkBlue: '#0645AD',
  darkestGray: '#333435',
  darkGray: '#808080',
  darkGreen: '#007448',
  darkPurple: '#0b0080',
  gray: '#A6A6A6',
  green: '#03A007',
  lightestBlue: '#C6DBFF',
  lightBlue: '#A7D7F9',
  lightGray: '#E8E8E8',
  mediumBlue: '#2A82B3',
  mediumDarkGray: '#787878',
  mediumGray: '#A0A0A0',
  mediumLightBlue: '#84AEEC',
  mediumLightGray: '#C8C8C8',
  transparentBlack: 'rgba(0,0,0,0.3)',
  transparentBlue: 'rgba(209,248,255,0.67)',
  transparentWhite: 'rgba(255,255,255,0.58)',
  white: '#FFFFFF',
};

export const perlerColors = [
  { name: 'White', hex: '#F7F7F2' },
  { name: 'Light Gray', hex: '#BEC3BF' },
  { name: 'Gray', hex: '#96989C' },
  { name: 'Pewter', hex: '#93A19F' },
  { name: 'Charcoal', hex: '#545F5F' },
  { name: 'Dark Gray', hex: '#56575C' },
  { name: 'Black', hex: '#343234' },
  { name: 'Toasted Marshmallow', hex: '#F1E5D8' },
  { name: 'Sand', hex: '#EAC49F' },
  { name: 'Fawn', hex: '#D7B087' },
  { name: 'Tan', hex: '#CFA889' },
  { name: 'Light Brown', hex: '#9D7153' },
  { name: 'Brown', hex: '#6C524D' },
  { name: 'Rust', hex: '#A04E3F' },
  { name: 'Cranapple', hex: '#88404F' },
  { name: 'Cherry', hex: '#AD3345' },
  { name: 'Red', hex: '#C43A44' },
  { name: 'Tomato', hex: '#EA4241' },
  { name: 'Spice', hex: '#E35C44' },
  { name: 'Orange', hex: '#FF803E' },
  { name: 'Butterscotch', hex: '#E19A52' },
  { name: 'Apricot', hex: '#FFA967' },
  { name: 'Cheddar', hex: '#FFB64E' },
  { name: 'Yellow', hex: '#F9D737' },
  { name: 'Pastel Yellow', hex: '#FAEE8D' },
  { name: 'Cream', hex: '#EDE7BA' },
  { name: 'Sherbert', hex: '#E1EE7D' },
  { name: 'Prickly Pear', hex: '#CBD735' },
  { name: 'Kiwi Lime', hex: '#77CA4A' },
  { name: 'Bright Green', hex: '#54B160' },
  { name: 'Shamrock', hex: '#009654' },
  { name: 'Dark Green', hex: '#108355' },
  { name: 'Evergreen', hex: '#3C614F' },
  { name: 'Olive', hex: '#72763E' },
  { name: 'Fern', hex: '#7B9730' },
  { name: 'Pastel Green', hex: '#73D594' },
  { name: 'Light Green', hex: '#38C7AF' },
  { name: 'Parrot Green', hex: '#00968A' },
  { name: 'Teal', hex: '#368D97' },
  { name: 'Lagoon', hex: '#00ABB2' },
  { name: 'Toothpaste', hex: '#B0E8D5' },
  { name: 'Turquoise', hex: '#008FCC' },
  { name: "Robin's Egg", hex: '#B4D9DF' },
  { name: 'Pastel Blue', hex: '#63A9D6' },
  { name: 'Sky', hex: '#54CDE3' },
  { name: 'Light Blue', hex: '#278ACB' },
  { name: 'Cobalt', hex: '#0066B3' },
  { name: 'Dark Blue', hex: '#2B307C' },
  { name: 'Midnight', hex: '#162846' },
  { name: 'Periwinkle', hex: '#6C88BF' },
  { name: 'Blueberry Crème', hex: '#87A7E1' },
  { name: 'Mist', hex: '#9CB9C7' },
  { name: 'Light Lavender', hex: '#B4A6D3' },
  { name: 'Pastel Lavender', hex: '#9582BB' },
  { name: 'Purple', hex: '#6F5493' },
  { name: 'Plum', hex: '#B25FAA' },
  { name: 'Orchid', hex: '#B56C99' },
  { name: 'Raspberry', hex: '#AD3C6C' },
  { name: 'Magenta', hex: '#F34676' },
  { name: 'Pink', hex: '#E65794' },
  { name: 'Bubble Gum', hex: '#E16D9D' },
  { name: 'Flamingo', hex: '#FFB5BE' },
  { name: 'Peach', hex: '#FCC6B8' },
  { name: 'Blush', hex: '#FF9E8D' },
  { name: 'Salmon', hex: '#FF777F' },
  { name: 'Hot Coral', hex: '#FF6158' },
  // { name: 'Neon Green', hex: '#00AC4A' },
  // { name: 'Neon Yellow', hex: '#BDD200' },
  // { name: 'Neon Pink', hex: '#F15289' },
  // { name: 'Neon Orange', hex: '#FF8D2E' },
  // { name: 'Neon Blue', hex: '#2255B7' },
  // { name: 'Silver', hex: '#777B81' },
  // { name: 'Gold', hex: '#B57F45' },
  // { name: 'Copper', hex: '#97634E' },
  // { name: 'Clear', hex: '#9EA7AE' },
  // { name: 'Clear Blue', hex: '#7CD2F2' },
  // { name: 'Transparent Turquoise', hex: '#006D8B' },
  // { name: 'Pearl', hex: '#D8D6C7' },
  // { name: 'Pearl Pink', hex: '#E37BAD' },
  // { name: 'Pearl Light Pink', hex: '#CCA49B' },
  // { name: 'Pearl Coral', hex: '#E99591' },
  // { name: 'Pearl Yellow', hex: '#D1C66E' },
  // { name: 'Pearl Green', hex: '#84B095' },
  // { name: 'Pearl Light Blue', hex: '#7AAEA2' },
  // { name: 'Red Glitter', hex: '#9D382E' },
  // { name: 'Blue Glitter', hex: '#0069C0' },
  // { name: 'Purple Glitter', hex: '#694184' },
  // { name: 'Yellow Glitter', hex: '#BAB456' },
  // { name: 'Green Glitter', hex: '#00876E' },
  // { name: 'Clear Glitter', hex: '#A6A9B1' },
  // { name: 'Black Glitter', hex: '#383737' },
  // { name: 'White Glitter', hex: '#D0DBDE' },
  // { name: 'Pink Glitter', hex: '#E2587F' },
  // { name: 'Fairy Dust', hex: '#9BAF9E' },
  // { name: 'Kiwi Glitter', hex: '#559E45' },
  // { name: 'Glow Green', hex: '#AFC39D' },
  // { name: 'Glow Blue', hex: '#56ACBE' },
  // { name: 'Glow Pink', hex: '#EE75A8' },
  // { name: 'Glow Purple', hex: '#AE66B1' },
  // { name: 'Glow Orange', hex: '#EAAF6F' },
  // { name: 'Color Change Blue', hex: '#649DCF' },
  // { name: 'Color Change Purple', hex: '#9D74C4' },
  // { name: 'Color Change Pink', hex: '#CD699E' },
  // { name: 'Color Change Red', hex: '#C86069' },
  // { name: 'Color Change Green', hex: '#55AF7E' },
  // { name: 'Color Change Dark Green', hex: '#384E48' },
  // { name: 'Color Change Black', hex: '#494D4D' },
];

export const perlerHexStrings = perlerColors.map(color => color.hex);

export const gridColors = [
  colors.white,
  colors.lightGray,
];
